server:
  port: 8083

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/order_service_db
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092

resilience4j:
  circuitbreaker:
    instances:
      productService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka